/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1b1c19",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface": "#1c1b1b",
        "on-secondary-fixed-variant": "#474744",
        "primary-container": "#6d58ff",
        "surface": "#fcf9f8",
        "on-primary-container": "#fffaff",
        "on-tertiary-container": "#fdfbf5",
        "tertiary-container": "#74746f",
        "on-secondary-fixed": "#1b1c19",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#160066",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#474555",
        "inverse-surface": "#313030",
        "surface-container-high": "#eae7e7",
        "on-primary-fixed-variant": "#3e17d1",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#e1dfdb",
        "secondary-fixed": "#e4e2dd",
        "surface-dim": "#dcd9d9",
        "inverse-on-surface": "#f3f0ef",
        "tertiary": "#5b5c57",
        "error": "#ba1a1a",
        "outline": "#787587",
        "on-secondary-container": "#63635f",
        "background": "#fcf9f8",
        "primary-fixed-dim": "#c6bfff",
        "surface-tint": "#573ee8",
        "surface-container": "#f0eded",
        "on-tertiary-fixed-variant": "#464743",
        "primary": "#543ae5",
        "tertiary-fixed-dim": "#c7c7c1",
        "on-background": "#1c1b1b",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#c8c6c2",
        "surface-bright": "#fcf9f8",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed": "#e4dfff",
        "tertiary-fixed": "#e3e3dd",
        "surface-container-low": "#f6f3f2",
        "secondary": "#5e5e5b",
        "outline-variant": "#c8c4d8",
        "surface-variant": "#e5e2e1",
        "inverse-primary": "#c6bfff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "container-max": "960px",
        base: "8px",
        md: "24px",
        sm: "12px",
        xl: "64px",
        gutter: "24px",
        lg: "40px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/container-queries"),
    require("@tailwindcss/forms"),
  ],
};
