"""Add agent config

Revision ID: 276b021119a8
Revises: 427ff4de3cc8
Create Date: 2026-08-18 10:18:09.223910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '276b021119a8'
down_revision: Union[str, Sequence[str], None] = '427ff4de3cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('agent_knowledge', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('businesses', sa.Column('agent_tone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'agent_tone')
    op.drop_column('businesses', 'agent_knowledge')
    # ### end Alembic commands ###
