"""Add Twilio columns

Revision ID: 427ff4de3cc8
Revises: 66139fb19b49
Create Date: 2026-08-17 11:50:51.222177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427ff4de3cc8'
down_revision: Union[str, Sequence[str], None] = '66139fb19b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('encrypted_twilio_sid', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('encrypted_twilio_auth_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'encrypted_twilio_auth_token')
    op.drop_column('businesses', 'encrypted_twilio_sid')
    # ### end Alembic commands ###
