"""Add total_tokens_used

Revision ID: 4a601eda1741
Revises: 276b021119a8
Create Date: 2026-08-18 11:56:45.450258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a601eda1741'
down_revision: Union[str, Sequence[str], None] = '276b021119a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('total_tokens_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'total_tokens_used')
    # ### end Alembic commands ###
