"""Add twilio_phone_number to Business

Revision ID: 61180f25ffb2
Revises: 49a86c5cafdf
Create Date: 2026-08-20 09:40:20.892823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61180f25ffb2'
down_revision: Union[str, Sequence[str], None] = '49a86c5cafdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('twilio_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'twilio_phone_number')
    # ### end Alembic commands ###
