"""Add encrypted telegram token

Revision ID: 66139fb19b49
Revises: bfdd55415609
Create Date: 2026-08-15 21:56:55.441263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66139fb19b49'
down_revision: Union[str, Sequence[str], None] = 'bfdd55415609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('encrypted_telegram_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'encrypted_telegram_token')
    # ### end Alembic commands ###
