"""Add Phase 9a analytics fields

Revision ID: c652b7903552
Revises: 61180f25ffb2
Create Date: 2026-08-21 04:13:35.784955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c652b7903552'
down_revision: Union[str, Sequence[str], None] = '61180f25ffb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('satisfaction', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response_time_ms')
    op.drop_column('messages', 'tokens_used')
    op.drop_column('conversations', 'satisfaction')
    # ### end Alembic commands ###
