"""Add paystack subaccount fields and customer_id to payment

Revision ID: d5a7fb7d7dfe
Revises: e9c4b0c623bd
Create Date: 2026-08-22 14:45:18.234835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a7fb7d7dfe'
down_revision: Union[str, Sequence[str], None] = 'e9c4b0c623bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('paystack_subaccount_code', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('bank_account_number', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('bank_code', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('bank_account_name', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('customer_identifier', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_customer_identifier'), 'payments', ['customer_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_customer_identifier'), table_name='payments')
    op.drop_column('payments', 'customer_identifier')
    op.drop_column('businesses', 'bank_account_name')
    op.drop_column('businesses', 'bank_name')
    op.drop_column('businesses', 'bank_code')
    op.drop_column('businesses', 'bank_account_number')
    op.drop_column('businesses', 'paystack_subaccount_code')
    # ### end Alembic commands ###
